export const SEARCH_LOCATION_REQUEST = 'SEARCH_LOCATION_REQUEST'
export const SEARCH_LOCATION_SUCCESS = 'SEARCH_LOCATION_SUCCESS'
export const REQUEST_VENUES = 'REQUEST_VENUES'
export const RECEIVE_VENUES = 'RECEIVE_VENUES'
export const REQUEST_VENUES_FAILURE = 'REQUEST_VENUES_FAILURE'
export const INITIALIZE_PARSE = 'INITIALIZE_PARSE';

// export const SEARCH_LOCATION_BLOCKED = 'SEARCH_LOCATION_DENIED'
// export const SEARCH_LOCATION_UNBLOCK = 'SEARCH_LOCATION_UNBLOCK'

