export const GEOLOCATE_REQUEST = 'GEOLOCATE_REQUEST'
export const GEOLOCATE_SUCCESS = 'GEOLOCATE_SUCCESS'
export const INITIALIZE_PARSE = 'INITIALIZE_PARSE';
export const RECEIVE_VENUES = 'RECEIVE_VENUES'
export const REQUEST_VENUES = 'REQUEST_VENUES'
export const REQUEST_VENUES_FAILURE = 'REQUEST_VENUES_FAILURE'
export const SEARCH_LOCATION_REQUEST = 'SEARCH_LOCATION_REQUEST'
export const SEARCH_LOCATION_SUCCESS = 'SEARCH_LOCATION_SUCCESS'
