<?php namespace AgreableVenuesPlugin;

use AgreableVenuesPlugin\Helper;
$ns = Helper::get('agreable_namespace');

if( function_exists('register_field_group') ):

register_field_group(array (
  'key' => "options_group_{$ns}",
  'title' => 'Venues Settings',
  'fields' => array (
    array (
      'key' => "{$ns}_plugin_map_slug",
      'label' => 'Venues Map URL prefix',
      'name' => 'venues_map_slug',
      'prefix' => '',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'map',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => "{$ns}_plugin_brand",
      'label' => 'Brand - Choose which brand to filter Venues by',
      'name' => 'venues_brand',
      'prefix' => '',
      'type' => 'text',
      'instructions' => 'E.g. mr-hyde, emerald-street, shortlist, stylist. All lowercase and no spaces/hyphenated. Multiple brands accepted using comma delimination. Leave blank to show all.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => "{$ns}_plugin_firebase_api_key",
      'label' => 'Firebase API Key',
      'name' => 'venues_firebase_api_key',
      'prefix' => '',
      'type' => 'text',
      'instructions' => '',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'AIzaSyBTJAJMSpkPjEPbWkrlphZ4FQ1bsJum0eY',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => "{$ns}_plugin_firebase_auth_domain",
      'label' => 'Firebase Auth Domain',
      'name' => 'venues_firebase_auth_domain',
      'prefix' => '',
      'type' => 'text',
      'instructions' => '',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'venues-database.firebaseapp.com',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => "{$ns}_plugin_firebase_db_url",
      'label' => 'Firebase Database URL',
      'name' => 'venues_firebase_db_url',
      'prefix' => '',
      'type' => 'text',
      'instructions' => '',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'https://venues-database.firebaseio.com',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => "{$ns}_plugin_firebase_storage_bucket",
      'label' => 'Firebase Storage Bucket',
      'name' => 'venues_firebase_storage_bucket',
      'prefix' => '',
      'type' => 'text',
      'instructions' => 'This isn\'t used at the moment',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'venues-database.appspot.com',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => "{$ns}_plugin_map_tiles_url",
      'label' => 'Map Tiles URL',
      'name' => 'venues_map_tiles_url',
      'prefix' => '',
      'type' => 'text',
      'instructions' => '',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'https://{s}.tiles.mapbox.com/v4/{mapId}/{z}/{x}/{y}.png?access_token={token}',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => "{$ns}_plugin_map_mapbox_token",
      'label' => 'Mapbox Access Token',
      'name' => 'venues_map_mapbox_token',
      'prefix' => '',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => "{$ns}_plugin_map_mapbox_mapid",
      'label' => 'Mapbox Map ID',
      'name' => 'venues_map_mapbox_mapid',
      'prefix' => '',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'acf-options',
      ),
      array (
        'param' => 'current_user_role',
        'operator' => '==',
        'value' => 'administrator',
      ),
    ),
  ),
  'menu_order' => 1,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
));

endif;
